In [2]:
import pandas as pd
import sqlite3

In [4]:
orders = pd.read_csv("orders.csv")
orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [6]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         10000 non-null  int64
 1   user_id          10000 non-null  int64
 2   restaurant_id    10000 non-null  int64
 3   order_date       10000 non-null  object
 4   total_amount     10000 non-null  float64
 5   restaurant_name  10000 non-null  object
dtypes: float64(1), int64(3), object(2)
memory usage: 468.9+ KB

In [7]:
users = pd.read_json("users.json")
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [8]:
users.info

<bound method DataFrame.info of       user_id       name       city membership
0           1     User_1    Chennai    Regular
1           2     User_2       Pune       Gold
2           3     User_3  Bangalore       Gold
3           4     User_4  Bangalore    Regular
4           5     User_5       Pune       Gold
...       ...        ...        ...        ...
2995     2996  User_2996  Hyderabad       Gold
2996     2997  User_2997  Hyderabad    Regular
2997     2998  User_2998  Bangalore    Regular
2998     2999  User_2999       Pune    Regular
2999     3000  User_3000  Hyderabad       Gold

[3000 rows x 4 columns]>

In [9]:
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

with open("restaurants.sql", "r") as f:
    sql_script = f.read()

cursor.executescript(sql_script)

restaurants = pd.read_sql_query("SELECT * FROM restaurants", conn)
restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [11]:
restaurants.info

<bound method DataFrame.info of      restaurant_id restaurant_name  cuisine  rating
0                1    Restaurant_1  Chinese     4.8
1                2    Restaurant_2   Indian     4.1
2                3    Restaurant_3  Mexican     4.3
3                4    Restaurant_4  Chinese     4.1
4                5    Restaurant_5  Chinese     4.8
..             ...             ...      ...     ...
495            496  Restaurant_496   Indian     3.1
496            497  Restaurant_497  Mexican     4.4
497            498  Restaurant_498  Chinese     3.9
498            499  Restaurant_499  Mexican     4.9
499            500  Restaurant_500  Chinese     3.2

[500 rows x 4 columns]>

In [12]:
orders_users = pd.merge(
    orders, users, on="user_id", how="left"
)

final_df = pd.merge(
    orders_users, restaurants, on="restaurant_id", how="left"
)

final_df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [13]:
final_df.info

<bound method DataFrame.info of       order_id  user_id  restaurant_id  order_date  total_amount  \
0            1     2508            450  18-02-2023        842.97
1            2     2693            309  18-01-2023        546.68
2            3     2084            107  15-07-2023        163.93
3            4      319            224  04-10-2023       1155.97
4            5     1064            293  25-12-2023       1321.91
...        ...      ...            ...         ...           ...
9995      9996     2528            249  21-05-2023       1211.96
9996      9997     2867            267  06-08-2023       1188.05
9997      9998      522            420  11-11-2023        979.44
9998      9999      319            492  08-09-2023       1105.93
9999     10000      457            439  21-10-2023        879.58

                   restaurant_name_x       name       city membership  \
0                  New Foods Chinese  User_2508  Hyderabad    Regular
1     Ruchi Curry House Multicuisine  User_2693       Pune    Regular
2              Spice Kitchen Punjabi  User_2084    Chennai       Gold
3             Darbar Kitchen Non-Veg   User_319  Bangalore       Gold
4          Royal Eatery South Indian  User_1064       Pune    Regular
...                              ...        ...        ...        ...
9995      Royal Kitchen North Indian  User_2528  Hyderabad       Gold
9996             Darbar Cafe Punjabi  User_2867  Bangalore    Regular
9997           Ruchi Tiffins Chinese   User_522  Bangalore       Gold
9998    Swagath Kitchen North Indian   User_319  Bangalore       Gold
9999  Classic Cafe Family Restaurant   User_457    Chennai    Regular

     restaurant_name_y  cuisine  rating
0       Restaurant_450  Mexican     3.2
1       Restaurant_309   Indian     4.5
2       Restaurant_107  Mexican     4.0
3       Restaurant_224  Chinese     4.8
4       Restaurant_293  Italian     3.0
...                ...      ...     ...
9995    Restaurant_249  Italian     4.7
9996    Restaurant_267  Chinese     4.2
9997    Restaurant_420  Italian     4.0
9998    Restaurant_492  Italian     4.0
9999    Restaurant_439  Mexican     3.1

[10000 rows x 12 columns]>

In [14]:
len(final_df)

10000

In [15]:
final_df.to_csv("final_food_delivery_dataset.csv", index=False)

In [16]:
# Total orders
len(final_df)

# Gold member orders
final_df[final_df["membership"] == "Gold"].shape[0]

4987

In [17]:
final_df["user_id"].nunique()

2883

In [19]:
print("Final dataset created using LEFT JOIN. Project completed successfully")

Final dataset created using LEFT JOIN. Project completed successfully